# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae438b00efc9871ff6e65f71b4ec7312d1ee422b02cd665d1a7caa65e9c00f0dc241b1eaba7ab2f6a338652be6c960c537df27706ecbf7d02c641ddab813eb4c

test:
  secret_key_base: c069f20b9ddcebc0c15f40e5b63beaacbb16bec7c783d723a7c10eda9509fe0a039cc3cc5c47ac128eab70e23a42fdf1212593bbd8dc341dadc099ab607e3e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
